package solve.constants

const val IconsCatalogueApplyPath = "icons/catalogue/apply.png"
const val IconsCatalogueImagePath = "icons/catalogue/image.png"
const val IconsImporterCheckCirclePath = "icons/importer/check_circle.png"
const val IconsImporterDescriptionPath = "icons/importer/description.png"
const val IconsImporterErrorFilePath = "icons/importer/error_file.png"
const val IconsImporterErrorFolderPath = "icons/importer/error_folder.png"
const val IconsImporterPhotoPath = "icons/importer/photo.png"
const val IconsImporterWarningPath = "icons/importer/warning.png"
const val IconsSidePanelCataloguePath = "icons/sidepanel/catalogue.png"
const val IconsSidePanelVisualizationSettingsPath = "icons/sidepanel/visualization_settings.png"
const val IconsSettingsVisualizationEditPath = "icons/settings/visualization/edit.png"
const val IconsSettingsVisualizationLayerInvisiblePath = "icons/settings/visualization/layer_invisible.png"
const val IconsSettingsVisualizationLayerVisiblePath = "icons/settings/visualization/layer_visible.png"
const val IconsSettingsVisualizationLineLayerPath = "icons/settings/visualization/line_layer.png"
const val IconsSettingsVisualizationPlaneLayerPath = "icons/settings/visualization/plane_layer.png"
const val IconsSettingsVisualizationPointLayerPath = "icons/settings/visualization/point_layer.png"
const val IconsSettingsGridIncrementPath = "icons/settings/grid/increment.png"
const val IconsSettingsGridDecrementPath = "icons/settings/grid/decrement.png"
const val IconsSettingsGridGridPath = "icons/settings/grid/grid.png"
const val IconsImporterLoadingPath = "icons/importer/loading.gif"
