package solve.constants

// Application icons.
const val IconsCatalogueApplyPath = "icons/catalogue/apply.png"
const val IconsCatalogueImagePath = "icons/catalogue/image.png"
const val IconsImporterCheckCirclePath = "icons/importer/check_circle.png"
const val IconsImporterDescriptionPath = "icons/importer/description.png"
const val IconsImporterErrorFilePath = "icons/importer/error_file.png"
const val IconsImporterErrorFolderPath = "icons/importer/error_folder.png"
const val IconsImporterPhotoPath = "icons/importer/photo.png"
const val IconsImporterWarningPath = "icons/importer/warning.png"
const val IconsSettingsVisualizationEditPath = "icons/settings/visualization/edit.png"
const val IconsSettingsVisualizationLayerInvisiblePath = "icons/settings/visualization/layer_invisible.png"
const val IconsSettingsVisualizationLayerVisiblePath = "icons/settings/visualization/layer_visible.png"
const val IconsSettingsVisualizationLineLayerPath = "icons/settings/visualization/line_layer.png"
const val IconsSettingsVisualizationPlaneLayerPath = "icons/settings/visualization/plane_layer.png"
const val IconsSettingsVisualizationPointLayerPath = "icons/settings/visualization/point_layer.png"
const val IconsSettingsGridIncrementPath = "icons/settings/grid/increment.png"
const val IconsSettingsGridDecrementPath = "icons/settings/grid/decrement.png"
const val IconsAlertError = "icons/importer/Vector.png"
const val IconsImportFab = "icons/sidepanel/Import.png"
const val IconsPlugins = "icons/sidepanel/Plugins.png"
const val IconsProject = "/icons/sidepanel/Project.png"
const val IconsProjectFilled = "/icons/sidepanel/ProjectFilled.png"
const val IconsSettings = "icons/sidepanel/Settings.png"
const val IconsHelp = "icons/sidepanel/Help.png"
const val IconsLayers = "/icons/sidepanel/Layers.png"
const val IconsLayersFilled = "/icons/sidepanel/LayersFilled.png"
const val IconsGrid = "/icons/sidepanel/Grid.png"
const val IconsGridSelected = "/icons/sidepanel/GridSelected.png"

// Engine shaders.
const val ShadersDefaultVertexPath = "engine/shaders/default/sprite.vert"
const val ShadersDefaultFragmentPath = "engine/shaders/default/sprite.frag"
const val ShadersFrameVertexPath = "engine/shaders/frame/frame.vert"
const val ShadersFrameGeometryPath = "engine/shaders/frame/frame.geom"
const val ShadersFrameFragmentPath = "engine/shaders/frame/frame.frag"
const val ShadersPointLandmarkVertexPath = "engine/shaders/landmark/point/point.vert"
const val ShadersPointLandmarkFragmentPath = "engine/shaders/landmark/point/point.frag"
const val ShadersLineLandmarkVertexPath = "engine/shaders/landmark/line/line.vert"
const val ShadersLineLandmarkFragmentPath = "engine/shaders/landmark/line/line.frag"
const val ShadersPlaneLandmarkVertexPath = "engine/shaders/landmark/plane/plane.vert"
const val ShadersPlaneLandmarkFragmentPath = "engine/shaders/landmark/plane/plane.frag"
const val ShadersPointAssociationVertexPath = "engine/shaders/association/point/point.vert"
const val ShadersPointAssociationFragmentPath = "engine/shaders/association/point/point.frag"
