package solve.constants

const val IconsImporterCheckCirclePath = "icons/importer/check_circle.svg"
const val IconsImporterDescriptionPath = "icons/importer/description.svg"
const val IconsImporterErrorFilePath = "icons/importer/error_file.svg"
const val IconsImporterErrorFolderPath = "icons/importer/error_folder.svg"
const val IconsImporterPhotoPath = "icons/importer/photo.svg"
const val IconsImporterWarningPath = "icons/importer/warning.svg"
const val IconsSettingsVisualizationEditPath = "icons/settings/visualization/edit.svg"
const val IconsSettingsVisualizationLayerInvisiblePath = "icons/settings/visualization/layer_invisible.svg"
const val IconsSettingsVisualizationLayerVisiblePath = "icons/settings/visualization/layer_visible.svg"
const val IconsSettingsGridIncrementPath = "icons/settings/grid/increment.svg"
const val IconsSettingsGridDecrementPath = "icons/settings/grid/decrement.svg"
const val IconsAlertError = "icons/importer/alert_error.svg"
const val IconsImportFab = "icons/sidepanel/import.svg"
const val IconsPlugins = "icons/sidepanel/plugins.svg"
const val IconsProject = "/icons/sidepanel/project.svg"
const val IconsProjectFilled = "/icons/sidepanel/project_selected.svg"
const val IconsSettings = "icons/sidepanel/settings.svg"
const val IconsHelp = "icons/sidepanel/help.svg"
const val IconsLayers = "/icons/sidepanel/layers.svg"
const val IconsLayersFilled = "/icons/sidepanel/layers_selected.svg"
const val IconsGrid = "/icons/sidepanel/grid.svg"
const val IconsGridSelected = "/icons/sidepanel/grid_selected.svg"
const val IconsFiltersAddPath = "icons/filters/add.svg"
const val IconsFiltersOrCheckBoxPath = "icons/filters/or_checkbox.svg"
const val IconsCataloguePlaceholder = "icons/placeholders/catalogue_placeholder.svg"
const val IconsScenePlaceholder = "icons/placeholders/scene_placeholder.svg"

// Common icons.
const val IconsEditPath = "icons/common/edit.svg"
const val IconsDeletePath = "icons/common/delete.svg"
const val IconsApp = "/icons/logo.png"
